name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.source }}
    strategy:
      matrix:
        target: [armv7-unknown-linux-musleabihf, aarch64-unknown-linux-musl]
        source: [logger, raspberry-pi/ds18b20]
        include:
          - target: x86_64-unknown-linux-musl
            source: logger
            config: "services co2db.json-example installer.sh"
          - config: "services co2db.json-example installer.sh"
            source: logger
          - config: "ds18b20_pub.service ds18b20.json-example installer.sh"
            source: raspberry-pi/ds18b20

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract crate information
      shell: bash
      run: |
        echo "PACKAGE_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> $GITHUB_ENV
    - name: Install Rust toolchain
      run: |
        rustup target add ${{ matrix.target }}
        cargo install cross
    - name: Build package
      run: |
        cross build --release --bins --target ${{ matrix.target }}
    - name: Build archive
      shell: bash
      run: |
        dirname="${{ env.PACKAGE_NAME }}-${GITHUB_REF#refs/tags/}-${{ matrix.target }}"
        mkdir "$dirname"
        bins=$(grep -A1 '\[\[bin\]\]' Cargo.toml | sed -n 's/^name = "\(.*\)"/\1/p')       
        targetdir="./target/${{ matrix.target }}/release/"
        for b in $bins; do mv "$targetdir"/$b "$dirname"; done
        cp -a ${{ matrix.config }} "$dirname"
        tar -czf "${{ github.workspace }}/${dirname}.tar.gz" "$dirname"
        echo "ASSET=${dirname}.tar.gz" >> $GITHUB_ENV
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ASSET }}
        path: ${{ env.ASSET }}

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: downloads
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: downloads/*
